### PR TITLE
updating xcodeproj, the new version will generate pbx using json format

### PR DESCRIPTION
**Pull request by thiago-lioy-movile**
This PR solves this [issue](https://github.com/venmo/synx/issues/105) .

### CODE REVIEW

**Comment by rafalwojcik** [comment]
Anyone can merge this? @marklarr?

**Comment by rafalwojcik** [comment]
@thiago-lioy-movile please change it to newest release "1.0.0.beta.4" and then @marklarr please merge this request with version bump

**Comment by rafalwojcik** [comment]
@marklarr I can help you maintain this library if you want. Just give me read/write permissions.

**Comment by marklarr** [comment]
Sorry, I am just seeing this now. I will merge today when I get to my
computer

**Comment by arkichek** [comment]
Version 1.0.0 has been released already.

**Comment by louoso** [comment]
Can anyone comment on when this dependency will be updated?

**Comment by marklarr** [comment]
Sorry for the wait, everybody. Updating to `1.0.0` thru https://github.com/venmo/synx/pull/109 now

**Pull request closed without merging**
