### PR TITLE
updated hash syntax

### PR DESCRIPTION
**Pull request by askl56**
updated hash syntax to Ruby 1.9

### CODE REVIEW

**Comment by marklarr** [comment]
I actually use the hash rockets on purpose. I sort of just like them better, /shrug, if anyone feels strongly about it to convince me otherwise, I'm all ears.

**Comment by askl56** [comment]
The most logical reason is that it makes the syntax uniform with JSON.

**Comment by askl56** [comment]
However I get that that is somewhat aesthetic so by all means let me know if you don't want it. I just know that is why it was introduced.

**Comment by marklarr** [comment]
I think the main thing for me is that the 1.9 syntax is pretty much a sugar on top of the hash-rocket that is less versatile. I'm not entirely sure, but I'm pretty sure it only works for symbols. And it's just kinda weird IMO, because they don't look like symbols, they just looks like JSON.

So this wouldn't work, for example
```ruby
{
   "value": 1
}
```

but this would
```ruby
{
   "value" => 1
}
```

Normally, I just go with whatever the app I'm working in is using, because I prefer consistency over all. But, when I get to start a new app and make the choice for myself, I'll always go with hash-rockets because I feel like they are less limiting and more true to what's actually happening.

**Comment by askl56** [comment]
Fair enough. Should I close it?

**Comment by marklarr** [comment]
If that's okay with you :), I can

**Pull request closed without merging**
